name: Update readme cards

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - readme-cards
    paths:
      - ".github/workflows/readme-cards.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v6

      - name: Generate stats card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&bg_color=ffffff00&text_color=888888&hide_border=true&hide_title=true"
          path: stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate top languages card
        uses: readme-tools/github-readme-stats-action@main
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}&bg_color=ffffff00&text_color=888888&hide_border=true&hide_title=true&layout=compact&exclude_repo=Samsung-Notes-Port,Samsung-Weather-Port,Samsung-Calculator-Port"
          path: top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.svg
          git commit -m "Update readme cards" || exit 0
          git push
